### ISSUE TITLE
Failing Client Install - Running Client and Server on Security Onion Beta3 for testing

### ISSUE THREAD

**Issue by ID1010TERROR** [weslambert/securityonion-grr#1]
### Background: 
I've installed GRR Server on-top of an existing SecurityOnion Beta3 system (This isn't a fresh install).
I did this using the new install script here: 
https://github.com/Security-Onion-Solutions/security-onion/wiki/GRR

**For the _Server_ this appears to work without any issues.**

### The Problem:
When I attempt to install the client (on the same system as the GRR server - SecurityOnion) 
by pulling the .deb file from the server as shown here:
https://grr-doc.readthedocs.io/en/v3.2.1/deploying-grr-clients/overview.htmls
and installing the .deb file as shown here:
https://grr-doc.readthedocs.io/en/v3.2.1/deploying-grr-clients/on-linux.html

The install of package grr_3.2.1.1_i386.deb fails and gives the following error:
sudo dpkg -i grr_3.2.1.1_i386.deb 

```
sudo dpkg -i grr_3.2.1.1_i386.deb 
(Reading database ... 157274 files and directories currently installed.)
Preparing to unpack grr_3.2.1.1_i386.deb ...
Unpacking grr (3211-1) over (3211-1) ...
Setting up grr (3211-1) ...
/var/lib/dpkg/info/grr.postinst: 13: /var/lib/dpkg/info/grr.postinst: /usr/lib/grr/grr_3.2.1.1_i386/grrd: not found
dpkg: error processing package grr (--install):
 subprocess installed post-installation script returned error exit status 127
Processing triggers for ureadahead (0.100.0-16) ...
Errors were encountered while processing:
 grr
```
I have verified that grrd is indeed in the specified path:  /usr/lib/grr/grr_3.2.1.1_i386/

#### Additional Info:
I'm running Security Onion as a Guest OS on Virtualbox 5.1.30, which is Hosted on a Debian 9.3 system. 

### Related issue:
- [Windows Client Unable to connect to GRR Server](https://github.com/weslambert/securityonion-grr/issues/2)

### References:

- [Original discussion on Google Groups](https://groups.google.com/forum/#!topic/security-onion/GrzL6VwC80k)
- [SecurityOnion GRR Install script](https://github.com/Security-Onion-Solutions/security-onion/wiki/GRR)
- [Deploying GRR Clients](https://grr-doc.readthedocs.io/en/v3.2.1/deploying-grr-clients/overview.htmls)
- [Deploying GRR Client on Linux](https://grr-doc.readthedocs.io/en/v3.2.1/deploying-grr-clients/on-linux.html)

Thanks, 
Jay

**Comment by weslambert** [comment]
Have you tried installing the 64-bit package to see if you get the same result?  

Thanks,
Wes

**Comment by ID1010TERROR** [comment]
Unfortunately, this version of the GRR Server doesn't seem to offer a 64-bit Debian package.
![image](https://user-images.githubusercontent.com/23456586/34919792-adb4477e-f936-11e7-9576-24c46122b569.png)

**Comment by weslambert** [comment]
Strange, I was just testing from a fresh install from the latest install script and have the following:

![image](https://user-images.githubusercontent.com/16829864/34919883-bf8d9878-f937-11e7-8c7d-a29c58f666dc.png)

You may want to try starting from a fresh install, if possible.

Thanks,
Wes

**Comment by ID1010TERROR** [comment]
A fresh install would be fine, please verify that you mean a complete reinstall of SecurityOnion and GRR, or just the GRR container. I'm currently running the securityonion-14.04.5.6.iso and used the script as it was 2 days ago. That said, I had not updated the SecurityOnion image prior to running the GRR scripts.

**Comment by weslambert** [comment]
No problem, Jay.

Please start with a fully updated Security Onion installation, and then
pull down the GRR Docker container per the securityonion-grr install
instructions.

Thanks,
Wes

**Comment by ID1010TERROR** [comment]
Update: Performing the fresh install has given me access to the adm64.deb binary. 
More to follow shortly.

**Comment by ID1010TERROR** [comment]
### Issue is Resolved
By reinstalling a fresh instance of SecurityOnion and using the updated scripts I was given access to the working grr_3.2.11_amd64.deb client binary. The client is now able to communicate with the server without issue.

Thanks!
-Jay

**Comment by weslambert** [comment]
Glad to hear.  Let me know if you have any more issues/feedback.

Thanks,
Wes

On Jan 14, 2018 5:03 PM, "Jay" <notifications@github.com> wrote:

Issue is Resolved

By reinstalling a fresh instance of SecurityOnion and using the updated
scripts I was given access to the working grr_3.2.11_amd64.deb client
binary. The client is now able to communicate with the server without issue.

Thanks!
-Jay

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/weslambert/securityonion-grr/issues/1#issuecomment-357546322>,
or mute the thread
